# Bot access token for discord.
# [SECURITY] These bot tokens should be treated like secrets as they allow the bot program to connect to Discord servers.
discord_token: <DISCORD_BOT_TOKEN>

# This is for testing out commands with another bot, optional.
operator_token: <DISCORD_OPERATOR_BOT_TOKEN>
operator_mode: False

# ID of the role to use admin commands.
# This must be a number, like 12345.
# To get your Discord Role ID, turn on developer mode in Discord, right click on your role, and select "Copy ID".
admin_role_id: <DISCORD_ADMIN_ROLE_ID>

# File to log system information to
log_file: log.txt

# Number of seconds to wait between processing a user's message. Spam protection
rate_limit: 60

# Add plans IDs and their associated role IDs here.
# The plan ID number on the left hand side must be a string, like '12345', and not 12345
# To get your plan ID, go to https://www.fanbox.cc/manage/plans, then click edit on the plan.
# The plan ID will be in the address bar. Replace '12345' with your own plan ID.
# <ROLE_ID> must be a number, same as above.
# To get the role ID, turn on developer mode in Discord, go to your server settings, then Roles,
# then right click on the role and select "Copy Role ID"
plan_roles:
  '12345': <ROLE_ID>

# Disallow multiple users from using the same Pixiv ID.
strict_access: False

# Check if the user is simply subscribed to a plan or not at this moment instead of using transaction records.
# This is "less fair" access than the transactions method, and the user must be subscribed when submitting for access.
only_check_current_sub: False

# Check transactions only from the current month (and the previous month if the current date is within `leeway_days`
# of the beginning of the current month). This only applies when `only_check_current_sub` is False.
only_check_recent_txns: False

# Periodic cleanup routines. Only runs after user activity
cleanup:
  # If we should even run cleanup routines at all
  run: False
  # Run only if it has been X hours since the last run
  period_hours: 24
  # Purge no-roll members older than X hours
  member_age_hours: 24

# Automatically update a user's role when it seems like their role will change.
auto_role_update:
  run: False
  period_hours: 24
  # Number of days to extend the stop date for a derole. Can help for the possible
  # lapse in Fanbox transactions at the beginning of the month.
  leeway_days: 5

# Messages to return to the user for each condition
system_messages:
  rate_limited: "Rate limited, please wait {rate_limit} seconds.\nレートが制限されていますので、{rate_limit}秒お待ちください。"
  no_id_found: "Cannot detect a user ID in your message.\nメッセージ内のユーザーIDを検出できません。"
  access_denied: "Access denied for ID {id}.\nID{id}に対してアクセスが拒否されました。"
  id_bound: "Access denied. ID {id} is already bound to another user. Please contact the admin for assistance.\nアクセスが拒否されました。ID{id}はすでに別のユーザーにバインドされています。管理者にお問い合わせください。"
  access_granted: "Access granted. Please check the server for new channels!\nアクセスが許可されました。新しいチャンネルがないか、サーバーをチェックしてみてください！"
  system_error: "An error has occurred! The admin has been notified to fix it.\nエラーが発生しました！管理者が修正するように通知されています。"

# Update these with cookies from your FANBOX page. These are needed to contact the FANBOX API.
# To access your cookies with Chrome: Go to your FANBOX page -> Ctrl+Shift+J -> Application -> Cookies -> https://www.fanbox.cc
# All values filled in must be strings, so if it's a number, you must 'quote' it, like '12345'.
# [SECURITY] The values here should be treated like secrets, because they allow the bot to act on your behalf on FANBOX.
# You may need to pass a captcha in your browser before updating these!
session_cookies:
  cf_clearance: <CF_CLEARANCE>
  FANBOXSESSID: <FANBOXSESSID>
  p_ab_d_id: <P_AB_D_ID>
  p_ab_id_2: <P_AB_ID_2>
  p_ab_id: <P_AB_ID>
  privacy_policy_agreement: '7'
  privacy_policy_notification: '0'
  agreement_master_terms_of_use_202408: '1'

# Needed to contact the FANBOX API.
session_headers:
  accept: application/json, text/plain, */*
  accept-language: en-US,en;q=0.5
  sec-fetch-dest: empty
  sec-fetch-mode: cors
  sec-fetch-site: same-site
  TE: trailers
  referer: https://www.fanbox.cc/
  origin: https://www.fanbox.cc
  # Get this from the network tab in your browser. Pick a random request and look at the headers tab. `User-Agent` should be near the bottom.
  # This will need to be updated every time your browser is updated.
  user-agent: <USER-AGENT>
